import fs from 'fs';
import path from 'path';

const OUTPUT_DIR = path.join(__dirname, 'output');
const MIGRATION_FILE = path.join(__dirname, '../supabase/migrations/20260115041616_seed_math_rocket_questions.sql');
const FILE_PREFIX = 'math_rocket_';

const generateSql = () => {
  const files = fs.readdirSync(OUTPUT_DIR).filter(file => file.endsWith('.json') && file.startsWith(FILE_PREFIX));
  
  // Create fresh migration content for the new file
  let sqlContent = '-- Seed questions table\n-- Generated by scripts/generate-seed-sql.ts\n\n';

  for (const file of files) {
    const filePath = path.join(OUTPUT_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    
    try {
      const questions = JSON.parse(content);
      
      if (!Array.isArray(questions)) {
        console.warn(`Skipping ${file}: content is not an array`);
        continue;
      }

      console.log(`Processing ${file} with ${questions.length} questions...`);

      if (questions.length === 0) continue;

      // Group inserts by file to avoid massive single transaction blocks if needed, 
      // but for this size, individual statements or chunks are fine. 
      // Let's do a bulk insert format for the file content:
      // INSERT INTO public.questions (id, game_id, difficulty, content) VALUES ...;
      
      const values = questions.map(q => {
        const id = q.id; // Assuming ID is present and valid UUID
        const gameId = q.game_id;
        const difficulty = q.difficulty;
        const contentJson = JSON.stringify(q.content).replace(/'/g, "''"); // Escape single quotes

        return `('${id}', '${gameId}', ${difficulty}, '${contentJson}')`;
      }).join(',\n');

      sqlContent += `\n-- Data from ${file}\nINSERT INTO public.questions (id, game_id, difficulty, content)\nVALUES\n${values}\nON CONFLICT (id) DO UPDATE SET\n  game_id = EXCLUDED.game_id,\n  difficulty = EXCLUDED.difficulty,\n  content = EXCLUDED.content;\n`;

    } catch (e) {
      console.error(`Error processing ${file}:`, e);
    }
  }

  fs.writeFileSync(MIGRATION_FILE, sqlContent);
  console.log(`Generated SQL to ${MIGRATION_FILE}`);
};

generateSql();
