-- Seed questions table
-- Generated by scripts/generate-seed-sql.ts


-- Data from ball_sort_1.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('8c209e05-e018-49ef-a9c5-9b73d1dcb9dc', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('c622887b-f983-4a7a-afe3-f4c3d415ff43', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('9103a048-041e-4c88-8d5f-40a140ed5739', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('dea67f45-299b-48b2-8ffa-46f497174272', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('bb03cad0-ef70-460c-9b9d-c8e5d5ee6c85', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('ed0d743a-4ed2-4bf0-a2e4-b792cc4cc845', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('54cc7c20-5a5b-4498-9e77-5024467ee132', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('ea640860-7fed-41a0-a2e0-28030b33a098', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('64b3c6fb-e4d1-4b13-ba70-8b35576c6811', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('c4c8e98d-7ea3-4d1e-8eb1-c4d897189f30', 'ball_sort', 1, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_10.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('f0b01f70-f063-4ec5-a625-0e65152f667a', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('88607074-fc9e-40f9-bada-a1530aa751ec', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('057798ca-6377-4815-bbf4-b3225539290c', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('9998dc38-e5af-4394-8c98-b5aec5608827', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('53c51710-a027-4256-a5bc-2303e3aa1ac4', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('6927cd01-326c-4ee4-ae76-4fedb019047c', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('e6bdd3d2-6c64-40d6-a136-adfd991ff8e5', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('8bcaa585-6f51-437d-be1a-898eccd00eb6', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('81e8e212-b1de-42cc-ac24-abbf4653a65d', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('52d83771-cf31-4249-b43e-3559c0a0800e', 'ball_sort', 10, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_2.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('7fa16585-9f3a-444c-9d1d-4f636df0b601', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('700a02bb-399d-496d-993b-84ef139fd4b8', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('abd472ac-917a-4052-88e0-c9c0352f7e72', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('4aa87133-9376-40bd-b39e-de19f9eaa16c', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('68f49639-81b5-4cd3-ab5a-497418ce8575', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('6847b07f-d486-4eec-8365-2890cad2e13e', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('f388fe92-b238-40fa-b296-7d4c9bd4b669', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('699911fe-84c5-4a9c-a4f6-63bde56b598c', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('af05af83-a2f7-49a5-a636-88bc779afaf3', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}'),
('17e0581c-778c-41d1-8fef-475b5b234713', 'ball_sort', 2, '{"type":"ball_sort","tubeCount":4,"capacityPerTube":4,"colorCount":2}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_3.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('6d11c155-9ef1-4dff-b310-1c53832cbf1b', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('dd9397e4-a6a0-4805-9758-f827cf5ab31f', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('52cc4d2e-e18a-4e89-b44f-e5144d45718a', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('0bd08ad9-413e-49cb-bfc8-4195ca357e03', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('77f23461-d360-4c86-af46-5112cc04f8c3', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('cfead2ec-0b63-4131-8021-b5b559269892', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('f1d51a28-69d9-4694-9965-17ecb6269263', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('0974c362-3fec-4d0a-b18b-cefde9aa853a', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('5a7214b5-7611-4026-8595-023f30ecfc92', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('c02ec157-7d31-46e5-8eda-42906d16aa7e', 'ball_sort', 3, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_4.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('1b5c520f-f702-4d43-a45c-ef374817a6ed', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('a87682cb-ac7b-4713-b7c5-3daa0a968783', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('e4d0c9d4-6a50-4062-8016-8139b09a0a38', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('3c476516-5f54-470b-b2d8-8417ec019c8e', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('051e1eca-5960-4a68-8e56-91c807ca7c37', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('49d33d47-5bb5-46c9-a700-7a73095d6bfe', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('ec66d297-ba96-4503-bcc8-a9f566828d42', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('7f2ceddc-4001-4c77-b147-fc1e35883cdc', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('8c84f738-0324-4a01-b824-a3e90eee8cd0', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}'),
('07eb8259-7fe1-4827-b47b-d99406ab47e8', 'ball_sort', 4, '{"type":"ball_sort","tubeCount":5,"capacityPerTube":4,"colorCount":3}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_5.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('58297f92-4ce9-476e-8b37-0e9c1b41f179', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('7072fdd8-adef-467a-b350-ce0bf0a241f8', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('8bc0d30b-18d1-44d8-b71b-0411260484de', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('7847fd05-efa0-45fb-bf6b-8ac810979335', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('015e7d52-6ce6-4d02-92bb-601618583522', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('025a7659-2aa7-46be-99f4-e2399999be82', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('00cb94af-c9bd-4fcf-ab32-403f6feba042', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('92299442-9f68-41f8-ab96-8b22c6f3f07f', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('9939c73f-ce0d-4a0b-9fc3-d7d919a6650c', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('3e958c6c-d0d1-4702-a710-1a2903b875ee', 'ball_sort', 5, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_6.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('ff27748a-62fb-43fd-bb9a-338634901632', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('08b7e239-c55a-462b-bd21-04259198fb65', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('c3961a57-4d63-4900-b9bc-d1ee3c215202', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('0b3cc35a-fe3b-4ccb-a5e4-d40c495b63a2', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('c94beabc-292c-4c56-b759-9ad330e3ba42', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('b730d23b-e273-469d-95c4-e2ca677d0fe4', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('fe8e2274-b3f0-41b0-ad61-e940620d7dab', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('5f0161c0-c47c-46af-a03a-834f861c8077', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('05825bfd-4d98-4023-a241-9468facf8c30', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}'),
('a8034642-135a-4825-8771-235efff0b1f3', 'ball_sort', 6, '{"type":"ball_sort","tubeCount":7,"capacityPerTube":4,"colorCount":5}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_7.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('2bf926bd-5ae8-4ac8-8a11-0fba654aa0e3', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('f897df30-bbda-4f1a-a7fe-077a59cbdb35', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('ee8dd830-7686-4295-98cc-ab31de39dc98', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('dc6b069c-fd18-43cc-bb51-e1542030e3a7', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('200dbf4f-ce82-49c5-83b5-0faef0a46077', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('e264b9b5-517d-4b93-9070-ab7b20d3820a', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('9e99dc56-9f2b-4037-817e-84769d5d8cc6', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('259ed8d4-980f-4ccc-9d38-2f267f541a81', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('75fb9dc0-723f-4795-90f0-322260ceaf12', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('ef4bc5d3-8b9d-4b97-b6e3-6329ceba29c4', 'ball_sort', 7, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_8.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('21aa19e3-d611-4787-aff2-662802b439ed', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('2c6768b3-8810-4b36-a696-4468f9a8cbaf', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('3a223204-5cc5-4202-a891-4a3f0c752647', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('6d9402b1-aa2c-41b0-94e3-51fe56888ba3', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('799f2cd2-458b-4ed0-ac92-1d6f4649ecd2', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('dea91550-2648-4181-96d8-babccb050d39', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('70a7cd62-6330-4ed3-be76-174946b8940c', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('33d768a1-44e4-4495-bebb-f2305e113991', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('cc657de6-5f9c-4949-9b9f-d2a8c608caa6', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}'),
('5c200df3-6be9-4411-b931-8de4ec471a8f', 'ball_sort', 8, '{"type":"ball_sort","tubeCount":9,"capacityPerTube":4,"colorCount":7}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;

-- Data from ball_sort_9.json
INSERT INTO public.questions (id, game_id, difficulty, content)
VALUES
('f1984785-331e-41c4-ac3b-f90da483a990', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('3ab1496d-761d-48af-ad39-94b7e1fd7fda', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('7387a017-d374-4805-8a7a-f70b874d54c3', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('16af51a5-7c6e-4e82-9a8c-5dcdc02e2fdd', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('d123d8cc-dd55-4a4e-96f1-012acd6654a7', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('468945ba-56fc-4386-a28e-c7d6ef95f58c', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('8021267e-2431-4094-bb43-d829f4b06d9a', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('70846f46-782f-48d3-a06d-0a6cd44e89aa', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('1392f04b-33c0-4871-b56b-349f70c2ec07', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}'),
('4581cfc1-c60b-4f89-b126-ba16c091945e', 'ball_sort', 9, '{"type":"ball_sort","tubeCount":12,"capacityPerTube":4,"colorCount":10}')
ON CONFLICT (id) DO UPDATE SET
  game_id = EXCLUDED.game_id,
  difficulty = EXCLUDED.difficulty,
  content = EXCLUDED.content;
